version: '3'
services:
  discordbot-pow:
    image: discordbot-pow
    container_name: discordbot-pow
    build: .
    pull_policy: always
    env_file: .env
    environment:
      - DEBUG=voiceRead.js:*,utils.js:*
    restart: always
