name: 新機能要望 (Feature Request)
description: 新規に追加するものはこちら
title: '[要望]: '
labels: ['enhancement']
body:
  - type: textarea
    id: request
    attributes:
      label: 要望
      description: 追加したい機能について記述してください。
    validations:
      required: true

  - type: markdown
    attributes:
      value: 'ご記入ありがとうございました。'
