name: cleanup caches by a branch
on:
  pull_request_target:
    types:
      - closed
  delete:
  workflow_dispatch:
    inputs:
      branchNames:
        description: '削除対象とするキャッシュのあるbranch(ref)のリスト'
        required: false
        type: string

permissions:
  contents: read

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2
        with:
          egress-policy: audit

      - name: Cleanup
        uses: 4m-mazi/souji-action@df02f74003831b23deb60cacf168747b0b9ab6f0 # v1.4.11
        with:
          branch-names: ${{ inputs.branchNames }}
