name: cleanup caches by a branch
on:
  pull_request_target:
    types:
      - closed
  delete:
  workflow_dispatch:
    inputs:
      branchNames:
        description: '削除対象とするキャッシュのあるbranch(ref)のリスト'
        required: false
        type: string

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Cleanup
        uses: 4m-mazi/souji-action@20f71e75c2af757e9c7c61391a51b88d593d17b8 # v1.4.0
        with:
          branch-names: ${{ inputs.branchNames }}
