name: cleanup caches by a branch
on:
  pull_request_target:
    types:
      - closed
  delete:
  workflow_dispatch:
    inputs:
      branchNames:
        description: '削除対象とするキャッシュのあるbranch(ref)のリスト'
        required: false
        type: string

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Cleanup
        uses: 4m-mazi/souji-action@bea3046bd3f644901f1beea84be0691782ab413d # v1.3.1
        with:
          branch-names: ${{ inputs.branchNames }}
