on:
  push:
    branches:
      - main

name: release

jobs:
  release-please:
    if: github.repository_owner == 'j-eoeo'
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release-please.outputs.release_created }}
      tag_name: ${{ steps.release-please.outputs.tag_name }}
    steps:
      - name: Generate a token
        id: generate_token
        uses: actions/create-github-app-token@86576b355dd19da0519e0bdb63d8edb5bcf76a25 # v1.7.0
        with:
          app-id: ${{ vars.EOEO_RELEASE_APP_ID }}
          private-key: ${{ secrets.EOEO_RELEASE_PRIVATE_KEY }}
      - uses: google-github-actions/release-please-action@cc61a07e2da466bebbc19b3a7dd01d6aecb20d1e # v4.0.2
        id: release-please
        with:
          token: ${{ steps.generate_token.outputs.token }}
          config-file: .github/files/release-please/release-please-config.json
          manifest-file: .github/files/release-please/.release-please-manifest.json
          skip-github-pull-request: ${{ startsWith(github.event.head_commit.message, 'release:') && github.event.head_commit.author.name == 'j-eoeo-release[bot]' }}

  docker-publish:
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created }}
    permissions:
      contents: write
      packages: write
    uses: ./.github/workflows/docker.yml
    with:
      tag-name: ${{ needs.release-please.outputs.tag_name }}

  publish-release:
    needs: [release-please, docker-publish]
    if: ${{ needs.release-please.outputs.release_created }}
    permissions:
      contents: write
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GH_REPO: ${{ github.repository }}
    runs-on: ubuntu-latest
    steps:
      - run: gh release edit ${{ needs.release-please.outputs.tag_name }} --draft=false

  get-pr-number:
    needs: [release-please]
    if: ${{ needs.release-please.outputs.release_created }}
    permissions: {}
    runs-on: ubuntu-latest
    outputs:
      pr_number: ${{ steps.pr-number.outputs.pr_number }}
    steps:
      - name: Get PR number
        id: pr-number
        run: |
          echo "pr_number=$(printf '${{ github.event.head_commit.message }}' | head -n1 | sed -nE 's/.+\(#([0-9]+)\)$/\1/p')" >> "$GITHUB_OUTPUT"

  add-comment:
    needs: [release-please, docker-publish, get-pr-number]
    if: ${{ needs.release-please.outputs.release_created }}
    permissions:
      pull-requests: write
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GH_REPO: ${{ github.repository }}
    runs-on: ubuntu-latest
    steps:
      - name: Add comment to PR
        run: |
          printf ':robot: Successfully published to ${{ needs.docker-publish.outputs.image_url }} :truck:\n```\n${{ join(needs.docker-publish.outputs.image_tags, '\n') }}\n```' \
          | gh pr comment ${{ needs.get-pr-number.outputs.pr_number }} --body-file=-

  label-published:
    needs: [release-please, docker-publish, get-pr-number]
    if: ${{ needs.release-please.outputs.release_created }}
    permissions:
      pull-requests: write
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GH_REPO: ${{ github.repository }}
    runs-on: ubuntu-latest
    steps:
      - name: Create published label
        run: |
          gh label create 'autorelease: published' --color=EDEDED || true
      - name: Change labels on PR
        run: |
          gh pr edit ${{ needs.get-pr-number.outputs.pr_number }} \
          --remove-label='autorelease: tagged' \
          --add-label='autorelease: published'
