name: Versioning
on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  versioning:
    name: 'Versioning'
    runs-on: ubuntu-22.04
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GH_REPO: ${{ github.repository }}
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
        with:
          fetch-depth: 0
      - name: Setup git
        run: |
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git config push.default current
      - run: bash -e ./.github/workflows/versioning/main.sh
